sudo: false
language: node_js
node_js:
- stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run build
- npm test
- npm update
- npm test
deploy:
  provider: npm
  email: iwata0303@gmail.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: S5NsBGrAgMYKkzftuKPiig2FWhBxPHQJ1MnZxU2lakXN1AhDqjV9aMkuGKDv9kKw7Y7Wbp4EE4QpB4nqd1YlZOH4Cfm3s2LZnuwaXSvnhgnYQ4SgtXX1gNEVISeYdK2q/bxWBH0TX5EqB+IPzgJRehlPgej7i4PabesNOVstkXzhFHerUoawAWZWs0Z9d3gar+hT8ERwg+1pqfGGF+ONbivzXyHY5CCf+p+R3v53cdXwzUcB583SU2luGkNdLC20z08ESMBVX7/COAyPEAeU0SkdnrAr/ZGeFCoh9zMCx1BpWidDKj7d/ZTzveXIzp/ZSCUMmI6z7lIIUS0S6XLfafYxLTHZHNiQEaewFEhRQryaP6GVwwdSoseTKoRDFQw4H+r7S451+Kz6GGe3HXWutxmySqon3/K9M9iQt0HvDte1+SuX/MMmia4XA/hbAI4sWt1HDlYnSX3IVAIXlaBukkTyvo4D5r1bUZFmB4glDBJ3SKWP8HvAUtoJl4lX3YUiO7ga2PjtEI36dCBmpW6qthV49ftgTiCF9R1JrHF58zYM184GPobBt7DUYSCIDLaUZT+QE7+6bxBrDsDsdHiW+goeEMpFNPPIe/L1Dh7ruWWzTgTk21Xq+OytvML31u3Q9Ji+1+nmzv7ZETee3b5Oox6GrpeQSc+W+p+6sUFOL+c=
